#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/alacritty/alacritty.yml
ln -s $DOTFILES/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml

rm -rf $HOME/.config/wezterm/wezterm.lua
ln -s $DOTFILES/wezterm/wezterm.lua $HOME/.config/wezterm/wezterm.lua
